<a href="https://colab.research.google.com/github/adibahsan/linear-regression-tensorflow/blob/master/Linear_Regression_With_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

print('Using TensorFlow version:', tf.__version__)
print('Devices available:', tf.config.list_physical_devices())

Using TensorFlow version: 2.3.0
Devices available: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')]


# TensorFlow Constants

In [41]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [42]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [43]:
## Data Type Changing
tf.convert_to_tensor([[1,2,3]], dtype=float)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [44]:
tf.convert_to_tensor([[1,2,3]]).numpy()

array([[1, 2, 3]], dtype=int32)

# Tensor Variables

In [45]:
tf.Variable([1,2,3])

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [46]:
# Mutable Values 
v = tf.Variable([1,2,3])
print('v is ',v)
v.assign([1,2,4])
print('v is ',v)


v is  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
v is  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 4], dtype=int32)>


Matrix Multiplication

In [47]:
c = tf.constant(np.random.randn(2,3))
v = tf.Variable(np.random.randn(3,1))
print (c,v)
result = tf.matmul(c,v)
print ('Matrix Multiplied',result)

tf.Tensor(
[[-0.00179379 -0.50131546 -1.24673897]
 [-0.85228137  1.04722896  0.79606358]], shape=(2, 3), dtype=float64) <tf.Variable 'Variable:0' shape=(3, 1) dtype=float64, numpy=
array([[-0.08939416],
       [ 0.22280847],
       [ 1.19746153]])>
Matrix Multiplied tf.Tensor(
[[-1.60445893]
 [ 1.26277597]], shape=(2, 1), dtype=float64)


#Automatic Differentiation

Let's take a simple equation as an example:
\begin{equation}
y = x^3 ; \frac{dy}{dx} = 3x^2
\end{equation}

In [48]:
x = tf.Variable(3.0)
with tf.GradientTape() as tp1:
  y = x**3

dy_dx = tp1.gradient(y,x)
print("gradient at x = {} is {}".format(x.numpy(),dy_dx.numpy()))

gradient at x = 3.0 is 27.0


In [49]:

with tf.GradientTape() as tp1:
  with tf.GradientTape() as tp2:
    y = x**3
  dy_dx = tp2.gradient(y,x)

d2y_dx2 = tp1.gradient(dy_dx, x)
print("2nd gradient at x = {} is {}".format(x.numpy(),d2y_dx2.numpy()))

2nd gradient at x = 3.0 is 18.0


# Contants Operation

In [50]:
x = tf.constant(3.0)
with tf.GradientTape() as tp1:
  # tp1.watch(x)
  y = x**3

dy_dx = tp1.gradient(y,x)
print("gradient at x is {}".format(dy_dx))

gradient at x is None


In [51]:
x = tf.constant(3.0)
with tf.GradientTape() as tp1:
  tp1.watch(x)
  y = x**3

dy_dx = tp1.gradient(y,x)
print("gradient at x = {} is {}".format(x.numpy(),dy_dx.numpy()))

gradient at x = 3.0 is 27.0
