<a href="https://colab.research.google.com/github/adibahsan/linear-regression-tensorflow/blob/master/Linear_Regression_With_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

print('Using TensorFlow version:', tf.__version__)
print('Devices available:', tf.config.list_physical_devices())

Using TensorFlow version: 2.3.0
Devices available: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')]


# TensorFlow Constants

In [2]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [3]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [6]:
## Data Type Changing
tf.convert_to_tensor([[1,2,3]], dtype=float)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [8]:
tf.convert_to_tensor([[1,2,3]]).numpy()

array([[1, 2, 3]], dtype=int32)

# Tensor Variables

In [10]:
tf.Variable([1,2,3])

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [17]:
# Mutable Values 
v = tf.Variable([1,2,3])
print('v is ',v)
v.assign([1,2,4])
print('v is ',v)


v is  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
v is  <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 4], dtype=int32)>


Matrix Multiplication

In [20]:
c = tf.constant(np.random.randn(2,3))
v = tf.Variable(np.random.randn(3,1))
print (c,v)
result = tf.matmul(c,v)
print ('Matrix Multiplied',result)

tf.Tensor(
[[-0.75225929  0.774843    1.82278024]
 [ 0.3050307  -1.10398819 -0.8841346 ]], shape=(2, 3), dtype=float64) <tf.Variable 'Variable:0' shape=(3, 1) dtype=float64, numpy=
array([[-0.78881812],
       [ 0.00982779],
       [-1.54821613]])>
Matrix Multiplied tf.Tensor(
[[-2.22104702]
 [ 1.11736794]], shape=(2, 1), dtype=float64)
